jwt:
  secretkey: khadkjfxnkmhdkzlmk456789hxdns87467rewunisy4678wuhxnjrfgcsi47rw93xiw3imsiwxhfin

spring:
  application:
    name: api-gateway

  #api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrderFilter
            - name: Authentication
              args:
                isEnabled: true
#           - RedirectTo=302, http://linkedin.com
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - name: Authentication
            - AddRequestHeader=X-Custom-Header, Sandeep
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
